########################################
# DEFAULT SETUP
########################################
api:
bluetooth:
cloud:
conversation:
default_config:
dialogflow:
ffmpeg:
history:
input_text:
lovelace_gen:
media_source:
mobile_app:
my:
person:
python_script:
stream:
sun:
system_health:
wake_on_lan:

########################################
# HTTPS
########################################
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxies

########################################
# THEMES
########################################
frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /local/card-mod.js

########################################
# IFTTT
########################################
ifttt:
  key: !secret ifttt_key

########################################
# ALEXA
########################################
alexa:
  smart_home:
    locale: fr-FR
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret amazon_client_id
    client_secret: !secret amazon_client_secret
    filter:
      exclude_domains:
        - group

########################################
# GOOGLE ASSISTANT
########################################
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !secret google_assistant_service_account
  report_state: true
  exposed_domains:
    - switch
    - light
    - camera
    - scene
    - sensor
    - script
    - climate
    - input_boolean
    - alarm_control_panel
    - media_player

########################################
# SPOTCAST
########################################
spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key
  country: FR #optional, added in 3.6.24

########################################
# TEXT TO SPEECH
########################################
tts:
  - platform: google_translate

########################################
# LOG VIEWER MODULE
########################################
logger:
  default: info
  logs:
    custom_components.tapo_control: debug

########################################
# CUSTOMIZE
########################################
homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config
    - /tmp
    - /config/www
    - /media

#######################################
# TELEGRAM
#######################################
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_group_id
      - !secret telegram_bot_my_chat_id

# Notifications pour groupe privé
notify:
  - platform: telegram
    name: Telegram groupe
    chat_id: !secret telegram_bot_group_id

  - platform: telegram
    name: Telegram perso
    chat_id: !secret telegram_bot_my_chat_id

########################################
# CALENDRIER BOULOT
########################################
ics_calendar:
  calendars:
      - name: "Calendrier boulot"
        url: !secret calendrier_boulot_url
        include_all_day: True
        download_interval: 1
        days: 2

########################################
# SCINDER
########################################

# Automatisations
automation: !include automations.yaml

# Binary sensor
binary_sensor: !include binary_sensor.yaml

# Caméras
camera: !include camera.yaml

# Commmand Line
command_line: !include command_line.yaml

# Device Tracker
device_tracker: !include device_tracker.yaml

# Doods2
image_processing: !include doods.yaml

# Group
group: !include groups.yaml

# Intent Scripts
intent_script: !include intent_script.yaml

# Recorder
recorder: !include recorder.yaml

# Rest Commands
rest_command: !include rest_commands.yaml

# Sensors
sensor: !include sensors.yaml

# Scenes
scene: !include scenes.yaml

# Scrape
scrape: !include scrape.yaml

# Scripts
script: !include scripts.yaml

# Shell Commands
shell_command: !include shell_commands.yaml

# Switchs
switch: !include switchs.yaml

# Templates
template: !include templates.yaml

# Utility Meters
utility_meter: !include utility_meter.yaml
